### PR TITLE
Support for MC 1.8

### PR DESCRIPTION
**Pull request by LucidSage**
I really like your mod and I really like the performance improvements in MC 1.8. I did not want to wait any longer to have these working together so I thought it was a good excuse to contribute something back.

Let me know if you have any suggestions for improvement!
<a href='#crh-start'></a><a href='#crh-data-%7B%22processed%22%3A%20%5B%22https%3A//github.com/odininon/EnchantingPlus-Scala/pull/21%23issuecomment-88176525%22%2C%20%22https%3A//github.com/odininon/EnchantingPlus-Scala/pull/21%23issuecomment-88177110%22%2C%20%22https%3A//github.com/odininon/EnchantingPlus-Scala/pull/21%23issuecomment-88211059%22%2C%20%22https%3A//github.com/odininon/EnchantingPlus-Scala/pull/21%23issuecomment-88239958%22%2C%20%22https%3A//github.com/odininon/EnchantingPlus-Scala/pull/21%23issuecomment-88254115%22%2C%20%22https%3A//github.com/odininon/EnchantingPlus-Scala/pull/21%23issuecomment-88278313%22%5D%2C%20%22comments%22%3A%20%7B%22General%20Comment%22%3A%20%7B%22html_url%22%3A%20%22https%3A//github.com/odininon/EnchantingPlus-Scala/pull/21%23issuecomment-88176525%22%2C%20%22comments%22%3A%20%5B%7B%22body%22%3A%20%22OMG%20%3C3%20I%27ll%20check%20out%20why%20Travis%20doesn%27t%20like%20it%20when%20I%20get%20home%20tonight.%22%2C%20%22created_at%22%3A%20%222015-03-31T17%3A17%3A34Z%22%2C%20%22user%22%3A%20%7B%22avatar_url%22%3A%20%22https%3A//avatars.githubusercontent.com/u/2147898%3Fv%3D3%22%2C%20%22html_url%22%3A%20%22https%3A//github.com/odininon%22%7D%7D%2C%20%7B%22body%22%3A%20%22%3A%2B1%3A%22%2C%20%22created_at%22%3A%20%222015-03-31T17%3A20%3A31Z%22%2C%20%22user%22%3A%20%7B%22avatar_url%22%3A%20%22https%3A//avatars.githubusercontent.com/u/2147898%3Fv%3D3%22%2C%20%22html_url%22%3A%20%22https%3A//github.com/odininon%22%7D%7D%2C%20%7B%22body%22%3A%20%22Thanks%2C%20i%27d%20appreciate%20the%20help.%20I%20had%20a%20look%20at%20the%20Travis%20build%20log%20but%20could%20not%20tell%20why%20it%20failed.%20I%20suspect%20it%20did%20not%20get%20the%20right%20forgeSrc%20library%20%281.8-11.14.1.1334%29%2C%20but%20it%20does%20not%20seem%20to%20show%20what%20version%20Travis%20used%20in%20the%20log.%20It%20did%20however%20seem%20to%20get%20the%20right%20MCP%20version%20%28stable_16%29.%5Cr%5Cn%22%2C%20%22created_at%22%3A%20%222015-03-31T19%3A05%3A44Z%22%2C%20%22user%22%3A%20%7B%22avatar_url%22%3A%20%22https%3A//avatars.githubusercontent.com/u/1417317%3Fv%3D3%22%2C%20%22html_url%22%3A%20%22https%3A//github.com/LucidSage%22%7D%7D%2C%20%7B%22body%22%3A%20%22Looks%20like%20the%20render%20features%20found%20in%20previous%20version%20are%20broken.%20I%27ll%20look%20into%20getting%20something%20like%20NOVA%20working%20for%20the%20custom%20model.%22%2C%20%22created_at%22%3A%20%222015-03-31T20%3A50%3A23Z%22%2C%20%22user%22%3A%20%7B%22avatar_url%22%3A%20%22https%3A//avatars.githubusercontent.com/u/2147898%3Fv%3D3%22%2C%20%22html_url%22%3A%20%22https%3A//github.com/odininon%22%7D%7D%2C%20%7B%22body%22%3A%20%22I%20cleaned%20out%20my%20IntelliJ%20setup%20and%20started%20from%20scratch%20and%20I%20am%20getting%20the%20same%20error%20as%20Travis.%20I%20must%20have%20had%20some%20stuff%20left%20around%20from%20pre-1.8.%20%20Sorry%20about%20the%20confusion.%22%2C%20%22created_at%22%3A%20%222015-03-31T21%3A19%3A29Z%22%2C%20%22user%22%3A%20%7B%22avatar_url%22%3A%20%22https%3A//avatars.githubusercontent.com/u/1417317%3Fv%3D3%22%2C%20%22html_url%22%3A%20%22https%3A//github.com/LucidSage%22%7D%7D%2C%20%7B%22body%22%3A%20%22Its%20fine%2C%20its%20actually%20one%20of%20the%201.7%20-%3E%201.8%20porting%20issues.%20I%27ll%20look%20into%20getting%20NOVA%20set%20up%20for%20it%20to%20load%20my%20custom%20models.%20%22%2C%20%22created_at%22%3A%20%222015-03-31T23%3A02%3A21Z%22%2C%20%22user%22%3A%20%7B%22avatar_url%22%3A%20%22https%3A//avatars.githubusercontent.com/u/2147898%3Fv%3D3%22%2C%20%22html_url%22%3A%20%22https%3A//github.com/odininon%22%7D%7D%5D%2C%20%22title%22%3A%20%22General%20Comment%22%7D%7D%7D'></a>
<a href='https://www.codereviewhub.com/'></a>
- [ ] <a href='#crh-comment-General Comment'></a> &nbsp;<b><a href='https://github.com/odininon/EnchantingPlus-Scala/pull/21#issuecomment-88176525'>General Comment</a></b>
- <a href='https://github.com/odininon'></a> OMG <3 I'll check out why Travis doesn't like it when I get home tonight.
- <a href='https://github.com/odininon'></a> :+1:
- <a href='https://github.com/LucidSage'></a> Thanks, i'd appreciate the help. I had a look at the Travis build log but could not tell why it failed. I suspect it did not get the right forgeSrc library (1.8-11.14.1.1334), but it does not seem to show what version Travis used in the log. It did however seem to get the right MCP version (stable_16).
- <a href='https://github.com/odininon'></a> Looks like the render features found in previous version are broken. I'll look into getting something like NOVA working for the custom model.
- <a href='https://github.com/LucidSage'></a> I cleaned out my IntelliJ setup and started from scratch and I am getting the same error as Travis. I must have had some stuff left around from pre-1.8.  Sorry about the confusion.
- <a href='https://github.com/odininon'></a> Its fine, its actually one of the 1.7 -> 1.8 porting issues. I'll look into getting NOVA set up for it to load my custom models.

<a href='https://www.codereviewhub.com/odininon/EnchantingPlus-Scala/pull/21?mark_as_completed=1'></a>&nbsp;<a href='https://www.codereviewhub.com/odininon/EnchantingPlus-Scala/pull/21?approve=1'></a>&nbsp;<a href='https://github.com/odininon/EnchantingPlus-Scala/pull/21'></a>
<a href='#crh-end'></a>

### CODE REVIEW

**Comment by odininon** [comment]
This pull request is now managed with CodeReviewHub. <a href='https://github.com/odininon/EnchantingPlus-Scala/pull/21'>Refresh</a>.<a href='#crh-update-none'></a>

**Comment by odininon** [comment]
OMG <3 I'll check out why Travis doesn't like it when I get home tonight.

**Comment by odininon** [comment]
:+1:

**Comment by LucidSage** [comment]
Thanks, i'd appreciate the help. I had a look at the Travis build log but could not tell why it failed. I suspect it did not get the right forgeSrc library (1.8-11.14.1.1334), but it does not seem to show what version Travis used in the log. It did however seem to get the right MCP version (stable_16).

**Comment by odininon** [comment]
Looks like the render features found in previous version are broken. I'll look into getting something like NOVA working for the custom model.

**Comment by LucidSage** [comment]
I cleaned out my IntelliJ setup and started from scratch and I am getting the same error as Travis. I must have had some stuff left around from pre-1.8.  Sorry about the confusion.

**Comment by odininon** [comment]
Its fine, its actually one of the 1.7 -> 1.8 porting issues. I'll look into getting NOVA set up for it to load my custom models.

**Comment by odininon** [comment]
Merged into Develop

**Comment by odininon** [comment]
http://minecraft.curseforge.com/mc-mods/59413-enchanting-plus/files/2232341

**Comment by LucidSage** [comment]
Are you getting this error when starting the client outside of the IDE?

java.lang.IllegalArgumentException: Multiple entries with same key: eplus=FMLMod:eplus{3.1.0a1} and eplus=FMLMod:eplus{3.1.0a1}

So if I add the mod, it loads twice. If I remove the mod nothing loads. If I run from the IDE it works fine. I see this error all over the forums when I search for it, but no one seems to have a solution. Any ideas on what is going on here?

**Comment by odininon** [comment]
Interesting error. Honestly, I am not as familiar with 1.8 as I should be.

**Comment by odininon** [comment]
It seems that it is caused by having mutiple .mcmodinfo in the jar.

**Comment by odininon** [comment]
I can't inspect the jar until I leave work.

**Comment by LucidSage** [comment]
I checked that. Only one mcmod.info in the jar.
I also doubled checked on another computer that I have not done any dev on and it gets the same error. So I am very certain that it is a problem in the jar, not a duplicate file somewhere.
I am wondering about the scala build. It makes more than one class file in the jar per source file. For example:
EnchantingPlus$.class
EnchantingPlus.class
If the @Mode attribute is duplicated in both of those then it could explain this problem.
I am going to try changing that file to java instead of scala and see if it makes a difference.

**Comment by LucidSage** [comment]
Wohoo! That was it. I created a minimal java class to put the @Mod attribute on and that has fixed the problem. It requires a couple tweaks as well, but not too bad. I will test this a little more, setup a branch, and send another pull request your way.

**Pull request closed without merging**
